GET http://127.0.0.1:5000/api/threads/100 HTTP/1.1

###

POST http://127.0.0.1:5000/api/register HTTP/1.1
content-type: application/json

{
    "username": "yo",
    "password": "internetjanitor"
}

###

POST http://127.0.0.1:5000/api/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "internetjanitor"
}
###

POST http://127.0.0.1:5000/api/create_thread HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY2MDQ4ODk3MiwiZXhwIjoxNjYwNDkwNzcyLCJpc19hZG1pbiI6MX0.C7la7Og-f3RCmgZtZO4rcp2scxH6sN6JKMz1z_1v4Qg

{
    "title": "test",
    "body": "this thread was created from the api"
}

###

POST http://127.0.0.1:5000/api/delete_thread/10 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY2MDQ3NjI4OSwiZXhwIjoxNjYwNDc4MDg5LCJpc19hZG1pbiI6MX0.CnRp5JwOn4F0uQq8NHrIyIiqxpmvuiL4SFyWZ9zDCp8

{
    "title": "test",
    "body": "this thread was created from the api"
}

###

POST http://127.0.0.1:5000/api/comment/1 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY2MDQ3NjI4OSwiZXhwIjoxNjYwNDc4MDg5LCJpc19hZG1pbiI6MX0.CnRp5JwOn4F0uQq8NHrIyIiqxpmvuiL4SFyWZ9zDCp8

{
    "comment": "hi"
}
###

POST http://127.0.0.1:5000/api/delete_comment/25 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY2MDQ4ODk3MiwiZXhwIjoxNjYwNDkwNzcyLCJpc19hZG1pbiI6MX0.C7la7Og-f3RCmgZtZO4rcp2scxH6sN6JKMz1z_1v4Qg

###

POST http://127.0.0.1:5000/api/comment/1 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLdJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY2MDQ3NjI4OSwiZXhwIjoxNjYwNDc4MDg5LCJpc19hZG1pbiI6MX0.CnRp5JwOn4F0uQq8NHrIyIiqxpmvuiL4SFyWZ9zDCp8

{
    "comment": "hi"
}

###

POST http://127.0.0.1:5000/api/login HTTP/1.1
content-type: application/json

{
    "username": "lol",
    "password": "internetjanitor"
}

##########

GET http://127.0.0.1:5000/api/user/admin HTTP/1.1

###
GET http://127.0.0.1:5000/api/user/Cthon98/threads HTTP/1.1

###
GET http://127.0.0.1:5000/api/user/AzureDiamond/comments HTTP/1.1